name: GitHub Workflow as Kube
description: Process GitHub events with plugin architecture
author: carlory

branding:
  icon: heart
  color: red

inputs:
  github-token:
    description: GitHub token for API access
    required: true
    default: ${{ github.token }}
  plugins:
    description: Comma-separated list of plugins to enable
    required: false
    default: 'cat,dog,help,pony,size,yuks'

outputs:
  event_name:
    description: The name of the GitHub event
  event_guid:
    description: The unique identifier for this event
  repository:
    description: The repository name in owner/repo format
  plugins_enabled:
    description: List of enabled plugins
  cat_posted:
    description: Whether a cat image was posted
  dog_posted:
    description: Whether a dog image was posted
  pony_posted:
    description: Whether a pony image was posted
  issue_number:
    description: Issue number where action was taken
  help_action:
    description:
      The help action taken (help-added, good-first-issue-added, help-removed,
      good-first-issue-removed)
  hold_action:
    description: The hold action taken (hold-added, hold-removed)
  shrug_action:
    description: The shrug action taken (shrug-added, shrug-removed)
  joke_posted:
    description: Whether a joke was posted
  size_label:
    description: The size label assigned to a pull request
  size_lines:
    description: Number of lines changed in a pull request
  workflow_data:
    description:
      Complete workflow data in JSON format (context, payload, inputs,
      environment)

runs:
  using: node24
  main: dist/index.js
